export component AppWindow inherits Window {
    width: 240px;
    height: 240px;

    padding: 0;
    background: #2b2e35;
    animate background {
        duration: 1500ms;
        easing: ease-in-expo;
    }

    Rectangle {
        border-radius: 240px / 2;
        border-color: black;
        border-width: 1px;

        Rectangle {
            background: #ffc72c;
            border-color: #ffffff;
            border-width: 4px;

            border-radius: self.width / 2;
            width: 30px;
            height: 30px;

            x: root.width / 2 - (root.width / 2 / 2);
            y: 80px;
        }

        Rectangle {
            background: #ffc72c;
            border-color: #ffffff;
            border-width: 4px;

            border-radius: self.width / 2;
            width: 30px;
            height: 30px;

            x: root.width / 2 + (root.width / 2 / 4);
            y: 80px;
        }

        Rectangle {
            background: #ffc72c;
            border-color: #ffffff;
            border-width: 4px;
            x: (root.width / 2) - (root.width / 2 / 6);
            y: 160px;
            width: 40px;
            height: 20px;
        }
    }
}
